### ISSUE TITLE
ClassLoader Error

### ISSUE THREAD

**Issue by codewithmishra** [frieden84/DemaRQ#2]
Exception in thread "main" java.lang.NoClassDefFoundError: Lcom/aspose/words/Document;
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
        at java.base/java.lang.Class.getDeclaredFields(Class.java:2248)
        at org.apache.uima.fit.internal.ReflectionUtil.getFields(ReflectionUtil.java:60)
        at org.apache.uima.fit.factory.ConfigurationParameterFactory.createConfigurationData(ConfigurationParameterFactory.java:411)
        at org.apache.uima.fit.factory.ConfigurationParameterFactory.setParameters(ConfigurationParameterFactory.java:348)
        at org.apache.uima.fit.factory.CollectionReaderFactory.createReaderDescription(CollectionReaderFactory.java:795)
        at org.apache.uima.fit.factory.CollectionReaderFactory.createReaderDescription(CollectionReaderFactory.java:662)
        at org.apache.uima.fit.factory.CollectionReaderFactory.createReaderDescription(CollectionReaderFactory.java:599)
        at org.apache.uima.fit.factory.CollectionReaderFactory.createReaderDescription(CollectionReaderFactory.java:456)
        at lu.svv.saa.requirements.autofinding.pipelines.DemarcateRequirements.extractFeatures(DemarcateRequirements.java:72)
        at lu.svv.saa.requirements.autofinding.pipelines.DemarcateRequirements.main(DemarcateRequirements.java:64)
Caused by: java.lang.ClassNotFoundException: com.aspose.words.Document
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 12 more

**Comment by frieden84** [comment]
I repackaged the jar file. This is the best I can do. It works well on my end. I have Java 1.8.

**Comment by codewithmishra** [comment]
Caused by: java.io.IOException: Unable to load resource [classpath:/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/tagger-en-maxent.properties]: 

FileNotFoundException: No file found at [classpath:/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/tagger-en-maxent.properties]



Please make sure that [de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent] version [20120616.1] is on the classpath.

If the version shown here is not available, try a recent version.



If you are using Maven, add the following dependency to your pom.xml file:



<dependency>

  <groupId>de.tudarmstadt.ukp.dkpro.core</groupId>

  <artifactId>de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent</artifactId>

  <version>20120616.1</version>

</dependency>

I guess it is still missing some of the dependencies in pom.xml
